export const EMPLOYEE_GET='EMPLOYEE_GET'
export const EMPLOYEE_ADD="EMPLOYEE_ADD";
export const EMPLOYEE_DELETE='EMPLOYEE_DELETE'
export const EMPLOYEE_SINGLE_SELECT='EMPLOYEE_SINGLE_SELECT'
export const EMPLOYEE_UPDATE='EMPLOYEE_UPDATE'